// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCleprL1hsA5xJrcC91KwoBN6ZQRWlx-8M',
    appId: '1:695288825902:web:8031553688b86a7cfab7bf',
    messagingSenderId: '695288825902',
    projectId: 'psych-catalog-86f0e',
    authDomain: 'psych-catalog-86f0e.firebaseapp.com',
    storageBucket: 'psych-catalog-86f0e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq62O1vKtLqIMj9muTubuwKYcszQFXMxA',
    appId: '1:695288825902:android:04a277cfc2f95b3ffab7bf',
    messagingSenderId: '695288825902',
    projectId: 'psych-catalog-86f0e',
    storageBucket: 'psych-catalog-86f0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGE6wBWcIwUN0f6UYmS6w-CzQgy8zh2VA',
    appId: '1:695288825902:ios:3da2372918d4bb29fab7bf',
    messagingSenderId: '695288825902',
    projectId: 'psych-catalog-86f0e',
    storageBucket: 'psych-catalog-86f0e.firebasestorage.app',
    iosBundleId: 'com.example.psychCatalogFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGE6wBWcIwUN0f6UYmS6w-CzQgy8zh2VA',
    appId: '1:695288825902:ios:3da2372918d4bb29fab7bf',
    messagingSenderId: '695288825902',
    projectId: 'psych-catalog-86f0e',
    storageBucket: 'psych-catalog-86f0e.firebasestorage.app',
    iosBundleId: 'com.example.psychCatalogFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCleprL1hsA5xJrcC91KwoBN6ZQRWlx-8M',
    appId: '1:695288825902:web:13c0562cb9f4ce9efab7bf',
    messagingSenderId: '695288825902',
    projectId: 'psych-catalog-86f0e',
    authDomain: 'psych-catalog-86f0e.firebaseapp.com',
    storageBucket: 'psych-catalog-86f0e.firebasestorage.app',
  );
}
